import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import ts from 'typescript';
const require=createRequire(import.meta.url),code=ts.transpileModule(readFileSync(new URL('../lib/pix.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;
const events=new Map();const db={prepare(){return {bind(...values){return {async run(){events.set(values[0],values);}};}};}};
const module={exports:{}};new Function('require','exports','module',code)(id=>id==='@/db'?{database:()=>db}:id==='./security'?{decrypt:async x=>x}:require(id),module.exports,module);const {pollPix,publicPix,money}=module.exports;
assert.equal(money('5.001'),'5.00');assert.throws(()=>money(-1));assert.throws(()=>money(NaN));
const p={user_id:'qa',mp_secret:'APP_USR-TEST-DO-NOT-USE',mp_amount:'5.00',mp_email:'qa@example.test'};
let persisted=[],calls=[],response={id:'ORDER1',status:'action_required',transactions:{payments:[{status:'action_required',payment_method:{qr_code:'MOCK QR NOT PAYABLE'}}]}};
globalThis.fetch=async(url,options)=>{calls.push({url,options});return Response.json(response);};
let state=await pollPix({},p,async s=>persisted.push(structuredClone(s)));assert.equal(persisted.length,1);assert(persisted[0].pending.key);assert.equal(calls[0].options.headers['X-Idempotency-Key'],persisted[0].pending.key);assert.equal(JSON.parse(calls[0].options.body).total_amount,'5.00');assert.equal(state.charge.kind,'orders');assert(publicPix(state,true).qr_code_base64);console.log('PASS Orders payload, QR generation and persistent idempotency');
response={id:'ORDER1',status:'action_required',transactions:{payments:[{status:'pending'}]}};const pending=await pollPix(state,p,async()=>{});assert.equal(pending.charge.id,'ORDER1');assert.equal(events.size,0);
let i=0;globalThis.fetch=async(url,options)=>{if(i++===0)return Response.json({id:'ORDER1',status:'processed',transactions:{payments:[{status:'processed',status_detail:'accredited',amount:'5.00'}]}});return Response.json({id:'ORDER2',transactions:{payments:[{payment_method:{qr_code:'NEXT MOCK'}}]}});};
state=await pollPix(state,p,async s=>persisted.push(structuredClone(s)));assert.equal(events.size,1);assert.equal(state.charge.id,'ORDER2');assert.equal(JSON.parse(events.values().next().value[2]).amount,5);console.log('PASS approved donation event and QR renewal');
let intent;globalThis.fetch=async()=>{throw new Error('network timeout')};await assert.rejects(pollPix({},p,async s=>intent=structuredClone(s)),/Não foi possível/);assert(intent.pending.key);const key=intent.pending.key;
globalThis.fetch=async(url,o)=>{assert.equal(o.headers['X-Idempotency-Key'],key);return Response.json({id:123,status:'pending',point_of_interaction:{transaction_data:{qr_code:'LEGACY MOCK'}}});};
state=await pollPix(intent,{...p,mp_secret:'TEST-FAKE-CREDENTIAL'},async()=>{});assert.equal(state.charge.kind,'payments');console.log('PASS retry reuses idempotency and legacy Payments response');
globalThis.fetch=async()=>new Response('secret token should not be exposed',{status:401});await assert.rejects(pollPix({},p,async()=>{}),/recusou o Access Token/);console.log('PASS credential errors are sanitized');
