'use client';
import {useState,type FormEvent} from 'react';
import {Radio,ShieldCheck,ArrowUpRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';

export default function AuthScreen({initialMode='login'}:{initialMode?:'login'|'register'}){
 const [mode,setMode]=useState(initialMode),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){
  event.preventDefault();setBusy(true);setError('');
  try{const response=await fetch('/api/auth/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});const data=await response.json() as {detail?:string};if(!response.ok)throw new Error(data.detail||'Não foi possível continuar.');location.href='/dashboard';}
  catch(reason){setError((reason as Error).message)}finally{setBusy(false)}
 }
 return <div className="studio-shell auth-page"><header className="topbar"><a className="wordmark" href="/"><Radio size={23}/> LIVE GAMER <b>3D</b></a><span className="top-note">SEU ESTÚDIO, SEU MUNDO</span><span className="account"><ShieldCheck size={16}/> ÁREA DO CRIADOR</span></header><main><div className="heading"><div><span className="eyebrow">DO CHAT PARA O SEU PALCO</span><h1>Sua comunidade ganha vida.</h1><p>Escolha um mundo, prepare sua cena e leve tudo para o OBS.</p></div><span className="pill"><i/>ENTRADA DO CRIADOR</span></div><div className="workspace"><section><div className="preview-card"><img className="auth-scene" src="/images/minecraft-real.png" alt="Captura real do Mundo Minecraft no Live Gamer 3D"/></div></section><aside className="setup"><span className="eyebrow">BEM-VINDO AO LIVE GAMER</span><h2>{mode==='register'?'Crie sua área de criador.':'Seus biomas esperam por você.'}</h2><p>{mode==='register'?'Cadastre sua conta e escolha seu primeiro mundo.':'Entre para acessar seus biomas e estúdios.'}</p><Tabs value={mode} onValueChange={value=>{setMode(value as 'login'|'register');setError('')}} className="tabs"><TabsList><TabsTrigger value="login">Entrar</TabsTrigger><TabsTrigger value="register">Criar conta</TabsTrigger></TabsList></Tabs><form onSubmit={submit}>{mode==='register'&&<label className="form-field">Seu nome ou canal<input name="name" autoComplete="name" minLength={2} maxLength={64} required placeholder="Como você quer ser chamado?"/></label>}<label className="form-field">E-mail<input name="email" type="email" autoComplete="email" required maxLength={254} placeholder="voce@exemplo.com"/></label><label className="form-field">Senha<input name="password" type="password" autoComplete={mode==='register'?'new-password':'current-password'} required minLength={10} maxLength={72} placeholder="Pelo menos 10 caracteres"/></label>{error&&<p className="notice error" role="alert">{error}</p>}<button className="primary-button full-width" disabled={busy}>{busy?'Aguarde…':mode==='register'?'Criar minha conta':'Entrar na Área do Criador'}<ArrowUpRight size={18}/></button></form><div className="setup-note"><ShieldCheck size={21}/><strong>Um espaço só seu</strong><p>Suas configurações e credenciais Pix ficam vinculadas à sua conta.</p></div></aside></div></main></div>;
}
